import { AchievementDefinition } from '../types/achievements.js';
import { Era } from '../types/eras.js';

export const ACHIEVEMENT_DEFINITIONS: Record<string, AchievementDefinition> = {
  // Credit milestones
  firstCredits: {
    key: 'firstCredits',
    name: 'First Steps',
    description: 'Earn your first 100 credits on Terminus.',
    condition: { type: 'resourceTotal', resource: 'credits', amount: 100 },
    icon: 'star',
  },
  thousandCredits: {
    key: 'thousandCredits',
    name: 'Getting Started',
    description: 'Earn 1,000 lifetime credits. The colony takes root.',
    condition: { type: 'resourceTotal', resource: 'credits', amount: 1000 },
    reward: { type: 'clickMultiplier', value: 1.1 },
    icon: 'star',
  },
  millionCredits: {
    key: 'millionCredits',
    name: 'Foundation Fortune',
    description: 'Earn 1,000,000 lifetime credits. Terminus prospers.',
    condition: { type: 'resourceTotal', resource: 'credits', amount: 1e6 },
    reward: { type: 'globalMultiplier', value: 1.05 },
    icon: 'star',
  },
  billionCredits: {
    key: 'billionCredits',
    name: 'Galactic Mogul',
    description: 'Earn 1,000,000,000 lifetime credits. The Periphery takes notice.',
    condition: { type: 'resourceTotal', resource: 'credits', amount: 1e9 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'star',
  },
  trillionCredits: {
    key: 'trillionCredits',
    name: 'Imperial Wealth',
    description: 'Earn 1,000,000,000,000 lifetime credits. Rivaling the old Empire.',
    condition: { type: 'resourceTotal', resource: 'credits', amount: 1e12 },
    reward: { type: 'globalMultiplier', value: 1.15 },
    icon: 'crown',
  },

  // Click milestones
  hundredClicks: {
    key: 'hundredClicks',
    name: 'Clicker',
    description: 'Click 100 times. Every action shapes the Plan.',
    condition: { type: 'totalClicks', count: 100 },
    icon: 'click',
  },
  thousandClicks: {
    key: 'thousandClicks',
    name: 'Dedicated Clicker',
    description: 'Click 1,000 times. The Foundation is built one click at a time.',
    condition: { type: 'totalClicks', count: 1000 },
    reward: { type: 'clickMultiplier', value: 1.2 },
    icon: 'click',
  },
  tenThousandClicks: {
    key: 'tenThousandClicks',
    name: 'Obsessive Clicker',
    description: 'Click 10,000 times. Seldon would be impressed.',
    condition: { type: 'totalClicks', count: 10000 },
    reward: { type: 'clickMultiplier', value: 1.5 },
    icon: 'click',
  },

  // Building milestones
  firstBuilding: {
    key: 'firstBuilding',
    name: 'Builder',
    description: 'Build your first structure on Terminus.',
    condition: { type: 'totalBuildings', count: 1 },
    icon: 'building',
  },
  tenBuildings: {
    key: 'tenBuildings',
    name: 'Architect',
    description: 'Own 10 buildings. The colony grows.',
    condition: { type: 'totalBuildings', count: 10 },
    reward: { type: 'globalMultiplier', value: 1.05 },
    icon: 'building',
  },
  fiftyBuildings: {
    key: 'fiftyBuildings',
    name: 'City Planner',
    description: 'Own 50 buildings. Terminus City takes shape.',
    condition: { type: 'totalBuildings', count: 50 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'building',
  },
  hundredBuildings: {
    key: 'hundredBuildings',
    name: 'Master Builder',
    description: 'Own 100 buildings. A civilization on the edge of the galaxy.',
    condition: { type: 'totalBuildings', count: 100 },
    reward: { type: 'globalMultiplier', value: 1.15 },
    icon: 'building',
  },

  // Prestige milestones
  firstPrestige: {
    key: 'firstPrestige',
    name: 'First Seldon Crisis',
    description: 'Survive your first Seldon Crisis. The Plan moves forward.',
    condition: { type: 'prestigeCount', count: 1 },
    icon: 'prestige',
  },
  fivePrestige: {
    key: 'fivePrestige',
    name: 'Crisis Manager',
    description: 'Survive 5 Seldon Crises. History bends to your will.',
    condition: { type: 'prestigeCount', count: 5 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'prestige',
  },
  tenPrestige: {
    key: 'tenPrestige',
    name: 'Seldon Heir',
    description: 'Survive 10 Seldon Crises. You are the Plan incarnate.',
    condition: { type: 'prestigeCount', count: 10 },
    reward: { type: 'globalMultiplier', value: 1.2 },
    icon: 'prestige',
  },

  // Era milestones
  reachEra1: {
    key: 'reachEra1',
    name: 'Trading Begins',
    description: 'Reach the Trading Expansion era. From religion to commerce.',
    condition: { type: 'eraReached', era: Era.TradingExpansion },
    icon: 'era',
  },
  reachEra2: {
    key: 'reachEra2',
    name: 'Mind Over Matter',
    description: 'Reach the Psychological Influence era. The Second Foundation awakens.',
    condition: { type: 'eraReached', era: Era.PsychologicalInfluence },
    icon: 'era',
  },
  reachEra3: {
    key: 'reachEra3',
    name: 'Galaxia Dawns',
    description: 'Reach the Galactic Reunification era. One galaxy, one mind.',
    condition: { type: 'eraReached', era: Era.GalacticReunification },
    icon: 'era',
  },

  // Special
  firstShip: {
    key: 'firstShip',
    name: 'Shipwright',
    description: 'Build your first ship. The Foundation takes to the stars.',
    condition: { type: 'shipCount', count: 1 },
    icon: 'ship',
  },
  tenShips: {
    key: 'tenShips',
    name: 'Fleet Commander',
    description: 'Own 10 ships. A fleet worthy of the Foundation.',
    condition: { type: 'shipCount', count: 10 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'ship',
  },
  playOneHour: {
    key: 'playOneHour',
    name: 'Dedicated',
    description: 'Play for 1 hour. The Plan unfolds in real time.',
    condition: { type: 'playTime', seconds: 3600 },
    icon: 'time',
  },
  playTenHours: {
    key: 'playTenHours',
    name: 'Devoted',
    description: 'Play for 10 hours. A true guardian of the Plan.',
    condition: { type: 'playTime', seconds: 36000 },
    reward: { type: 'globalMultiplier', value: 1.05 },
    icon: 'time',
  },

  // --- Hero Achievements ---
  recruitSeldon: {
    key: 'recruitSeldon',
    name: "The Father's Plan",
    description: 'Recruit Hari Seldon. The architect of the Plan joins your cause.',
    condition: { type: 'heroUnlocked', hero: 'hariSeldon' },
    reward: { type: 'clickMultiplier', value: 1.1 },
    icon: 'hero',
  },
  recruitHardin: {
    key: 'recruitHardin',
    name: 'Violence is the Last Refuge',
    description: 'Recruit Salvor Hardin. The first Mayor stands with you.',
    condition: { type: 'heroUnlocked', hero: 'salvorHardin' },
    icon: 'hero',
  },
  recruitMallow: {
    key: 'recruitMallow',
    name: 'The Merchant Prince',
    description: 'Recruit Hober Mallow. Trade conquers where weapons cannot.',
    condition: { type: 'heroUnlocked', hero: 'hoberMallow' },
    icon: 'hero',
  },
  recruitGaalDornick: {
    key: 'recruitGaalDornick',
    name: 'The First Witness',
    description: 'Recruit Gaal Dornick. The one who saw the Plan begin.',
    condition: { type: 'heroUnlocked', hero: 'gaalDornick' },
    reward: { type: 'clickMultiplier', value: 1.05 },
    icon: 'hero',
  },
  recruitEmperorCleon: {
    key: 'recruitEmperorCleon',
    name: 'Imperial Endorsement',
    description: 'Recruit Emperor Cleon. Even empires bow to the Plan.',
    condition: { type: 'heroUnlocked', hero: 'emperorCleon' },
    reward: { type: 'clickMultiplier', value: 1.05 },
    icon: 'hero',
  },
  recruitTheMule: {
    key: 'recruitTheMule',
    name: 'The Unconverted',
    description: 'Recruit the Mule. The greatest deviation, now an ally.',
    condition: { type: 'heroUnlocked', hero: 'theMule' },
    reward: { type: 'globalMultiplier', value: 1.05 },
    icon: 'hero',
  },
  recruitDaneel: {
    key: 'recruitDaneel',
    name: 'Twenty Thousand Years',
    description: 'Recruit R. Daneel Olivaw. The eternal guardian reveals himself.',
    condition: { type: 'heroUnlocked', hero: 'daneelOlivaw' },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'hero',
  },
  fiveHeroes: {
    key: 'fiveHeroes',
    name: 'Growing Council',
    description: 'Recruit 5 heroes. A council forms around the Plan.',
    condition: { type: 'totalHeroes', count: 5 },
    reward: { type: 'globalMultiplier', value: 1.03 },
    icon: 'hero',
  },
  fifteenHeroes: {
    key: 'fifteenHeroes',
    name: 'Legends Assembled',
    description: 'Recruit 15 heroes. The greatest minds of the galaxy unite.',
    condition: { type: 'totalHeroes', count: 15 },
    reward: { type: 'globalMultiplier', value: 1.08 },
    icon: 'hero',
  },
  allHeroes: {
    key: 'allHeroes',
    name: 'The Complete Council',
    description: 'Recruit all 25 heroes. Every legend answers the call.',
    condition: { type: 'totalHeroes', count: 25 },
    reward: { type: 'globalMultiplier', value: 1.15 },
    icon: 'hero',
  },

  // --- Activity Achievements ---
  firstActivity: {
    key: 'firstActivity',
    name: 'Field Work',
    description: 'Complete your first activity. Every journey begins with a single step.',
    condition: { type: 'totalActivityCompletions', count: 1 },
    icon: 'research',
  },
  tenActivities: {
    key: 'tenActivities',
    name: 'Seasoned Operative',
    description: 'Complete 10 activities. Experience is the best teacher.',
    condition: { type: 'totalActivityCompletions', count: 10 },
    reward: { type: 'clickMultiplier', value: 1.1 },
    icon: 'research',
  },
  fiftyActivities: {
    key: 'fiftyActivities',
    name: 'Foundation Workhorse',
    description: 'Complete 50 activities. The backbone of the Foundation.',
    condition: { type: 'totalActivityCompletions', count: 50 },
    reward: { type: 'globalMultiplier', value: 1.05 },
    icon: 'research',
  },
  hundredActivities: {
    key: 'hundredActivities',
    name: 'Relentless',
    description: 'Complete 100 activities. Nothing can stop the Plan.',
    condition: { type: 'totalActivityCompletions', count: 100 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'research',
  },
  twoFiftyActivities: {
    key: 'twoFiftyActivities',
    name: 'Master of All Trades',
    description: 'Complete 250 activities. A true polymath of the Foundation.',
    condition: { type: 'totalActivityCompletions', count: 250 },
    reward: { type: 'globalMultiplier', value: 1.15 },
    icon: 'research',
  },

  // --- Upgrade Achievements ---
  tenUpgrades: {
    key: 'tenUpgrades',
    name: 'Tinkerer',
    description: 'Purchase 10 upgrades. Innovation takes hold.',
    condition: { type: 'upgradesPurchased', count: 10 },
    icon: 'upgrade',
  },
  fiftyUpgrades: {
    key: 'fiftyUpgrades',
    name: 'Innovator',
    description: 'Purchase 50 upgrades. Technology reshapes Terminus.',
    condition: { type: 'upgradesPurchased', count: 50 },
    reward: { type: 'globalMultiplier', value: 1.05 },
    icon: 'upgrade',
  },
  hundredUpgrades: {
    key: 'hundredUpgrades',
    name: 'Technological Revolution',
    description: 'Purchase 100 upgrades. The Foundation leads the galaxy in science.',
    condition: { type: 'upgradesPurchased', count: 100 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'upgrade',
  },
  hundredFiftyUpgrades: {
    key: 'hundredFiftyUpgrades',
    name: 'Encyclopedist',
    description: 'Purchase 150 upgrades. Knowledge is the true foundation.',
    condition: { type: 'upgradesPurchased', count: 150 },
    reward: { type: 'clickMultiplier', value: 1.2 },
    icon: 'upgrade',
  },

  // --- Trade Route Achievements ---
  firstTradeRoute: {
    key: 'firstTradeRoute',
    name: 'Open Markets',
    description: 'Unlock your first trade route. Commerce begins.',
    condition: { type: 'tradeRoutesUnlocked', count: 1 },
    icon: 'trade',
  },
  fiveTradeRoutes: {
    key: 'fiveTradeRoutes',
    name: 'Trade Network',
    description: 'Unlock 5 trade routes. A web of commerce spans the Periphery.',
    condition: { type: 'tradeRoutesUnlocked', count: 5 },
    reward: { type: 'resourceMultiplier', value: 1.05, resource: 'credits' },
    icon: 'trade',
  },
  allTradeRoutes: {
    key: 'allTradeRoutes',
    name: 'Galactic Commerce',
    description: 'Unlock all 10 trade routes. The galaxy trades at your command.',
    condition: { type: 'tradeRoutesUnlocked', count: 10 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'trade',
  },

  // --- Seldon Point Achievements ---
  tenSeldonPoints: {
    key: 'tenSeldonPoints',
    name: 'The Plan Begins',
    description: 'Earn 10 Seldon Points. The first threads of the Plan emerge.',
    condition: { type: 'seldonPoints', amount: 10 },
    icon: 'prestige',
  },
  hundredSeldonPoints: {
    key: 'hundredSeldonPoints',
    name: 'Psychohistorical Proof',
    description: 'Earn 100 Seldon Points. The math is undeniable.',
    condition: { type: 'seldonPoints', amount: 100 },
    reward: { type: 'globalMultiplier', value: 1.05 },
    icon: 'prestige',
  },
  thousandSeldonPoints: {
    key: 'thousandSeldonPoints',
    name: 'The Plan Converges',
    description: 'Earn 1,000 Seldon Points. History bends to psychohistory.',
    condition: { type: 'seldonPoints', amount: 1000 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'prestige',
  },
  tenThousandSeldonPoints: {
    key: 'tenThousandSeldonPoints',
    name: "Seldon's True Heir",
    description: 'Earn 10,000 Seldon Points. You have surpassed the master.',
    condition: { type: 'seldonPoints', amount: 10000 },
    reward: { type: 'globalMultiplier', value: 1.15 },
    icon: 'prestige',
  },

  // --- Extended Building Achievements ---
  twoHundredBuildings: {
    key: 'twoHundredBuildings',
    name: 'Galactic Civilization',
    description: 'Own 200 buildings. A civilization worthy of the stars.',
    condition: { type: 'totalBuildings', count: 200 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'building',
  },
  fiveHundredBuildings: {
    key: 'fiveHundredBuildings',
    name: 'Ecumenopolis',
    description: 'Own 500 buildings. Terminus rivals Trantor itself.',
    condition: { type: 'totalBuildings', count: 500 },
    reward: { type: 'globalMultiplier', value: 1.15 },
    icon: 'building',
  },
  encyclopediaArchiveTen: {
    key: 'encyclopediaArchiveTen',
    name: 'Encyclopedia Galactica',
    description: 'Own 10 Encyclopedia Archives. All knowledge, preserved.',
    condition: { type: 'buildingCount', building: 'encyclopediaArchive', count: 10 },
    reward: { type: 'resourceMultiplier', value: 1.05, resource: 'knowledge' },
    icon: 'building',
  },
  nuclearReactorTwentyFive: {
    key: 'nuclearReactorTwentyFive',
    name: 'Nuclear Supremacy',
    description: 'Own 25 Nuclear Reactors. The atom serves the Foundation.',
    condition: { type: 'buildingCount', building: 'nuclearReactor', count: 25 },
    reward: { type: 'resourceMultiplier', value: 1.05, resource: 'nuclearTech' },
    icon: 'building',
  },
  galaxiaCoreOne: {
    key: 'galaxiaCoreOne',
    name: 'Heart of Galaxia',
    description: 'Build a Galaxia Core. The dream of unity takes physical form.',
    condition: { type: 'buildingCount', building: 'galaxiaCore', count: 1 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'building',
  },

  // --- Extended Click Achievements ---
  fiftyThousandClicks: {
    key: 'fiftyThousandClicks',
    name: 'The Human Element',
    description: 'Click 50,000 times. Psychohistory cannot predict the individual.',
    condition: { type: 'totalClicks', count: 50000 },
    reward: { type: 'clickMultiplier', value: 1.3 },
    icon: 'click',
  },
  hundredThousandClicks: {
    key: 'hundredThousandClicks',
    name: 'Psychohistorical Variable',
    description: 'Click 100,000 times. You are the variable Seldon never predicted.',
    condition: { type: 'totalClicks', count: 100000 },
    reward: { type: 'clickMultiplier', value: 2.0 },
    icon: 'click',
  },

  // --- Extended Ship Achievements ---
  fiveShips: {
    key: 'fiveShips',
    name: 'Small Fleet',
    description: 'Own 5 ships. A modest squadron patrols your space.',
    condition: { type: 'shipCount', count: 5 },
    icon: 'ship',
  },
  twentyShips: {
    key: 'twentyShips',
    name: 'Armada',
    description: 'Own 20 ships. The Foundation projects power across the Periphery.',
    condition: { type: 'shipCount', count: 20 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'ship',
  },
  fiftyShips: {
    key: 'fiftyShips',
    name: 'Galactic Navy',
    description: 'Own 50 ships. No force in the galaxy can challenge your fleet.',
    condition: { type: 'shipCount', count: 50 },
    reward: { type: 'globalMultiplier', value: 1.15 },
    icon: 'ship',
  },

  // --- Extended Credit Milestones ---
  quadrillionCredits: {
    key: 'quadrillionCredits',
    name: "Foundation's Treasure",
    description: 'Earn 1,000,000,000,000,000 lifetime credits. Wealth beyond measure.',
    condition: { type: 'resourceTotal', resource: 'credits', amount: 1e15 },
    reward: { type: 'globalMultiplier', value: 1.2 },
    icon: 'star',
  },
  quintillionCredits: {
    key: 'quintillionCredits',
    name: 'Economic Singularity',
    description: 'Earn 1,000,000,000,000,000,000 lifetime credits. The economy transcends.',
    condition: { type: 'resourceTotal', resource: 'credits', amount: 1e18 },
    reward: { type: 'globalMultiplier', value: 1.25 },
    icon: 'star',
  },

  // --- Extended Prestige ---
  twentyPrestige: {
    key: 'twentyPrestige',
    name: 'Crisis Veteran',
    description: 'Survive 20 Seldon Crises. History has no surprises left for you.',
    condition: { type: 'prestigeCount', count: 20 },
    reward: { type: 'globalMultiplier', value: 1.15 },
    icon: 'prestige',
  },

  // --- Extended Play Time ---
  playHundredHours: {
    key: 'playHundredHours',
    name: 'Timeless',
    description: 'Play for 100 hours. Time itself bows to the Plan.',
    condition: { type: 'playTime', seconds: 360000 },
    reward: { type: 'globalMultiplier', value: 1.1 },
    icon: 'time',
  },
};

export const ALL_ACHIEVEMENT_KEYS = Object.keys(ACHIEVEMENT_DEFINITIONS);
