import { Era } from '../types/eras.js';
import { ActivityDefinition } from '../types/activities.js';

export const ACTIVITY_DEFINITIONS: Record<string, ActivityDefinition> = {
  // ═══════════════════════════════════════════════════════════════════════
  // TUTORIAL ACTIVITIES
  // ═══════════════════════════════════════════════════════════════════════

  vaultCalibration: {
    key: 'vaultCalibration',
    name: 'Calibrate the Vault',
    description: 'Perform the initial calibration of the Seldon Vault\'s holographic systems.',
    era: Era.ReligiousDominance,
    type: 'research',
    cost: { credits: 10 },
    durationSeconds: 5,
    rewards: [{ itemKey: 'primeRadiant', quantity: 1 }],
    repeatable: false,
    maxCompletions: 1,
  },
  terminusPatrol: {
    key: 'terminusPatrol',
    name: 'Terminus Perimeter Scan',
    description: 'Scout the colony\'s perimeter to map safe zones and potential resource deposits.',
    era: Era.ReligiousDominance,
    type: 'mission',
    cost: { credits: 10 },
    durationSeconds: 5,
    rewards: [{ itemKey: 'atomicAshtray', quantity: 1 }],
    repeatable: false,
    maxCompletions: 1,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // ERA 0: RELIGIOUS DOMINANCE
  // ═══════════════════════════════════════════════════════════════════════

  // ─── Era 0 Research Projects ─────────────────────────────────────────

  psychohistoryPrimer: {
    key: 'psychohistoryPrimer',
    name: 'Compile Psychohistory Primer',
    description: 'Compile the foundational texts of psychohistory for future generations of scholars.',
    era: Era.ReligiousDominance,
    type: 'research',
    cost: { knowledge: 5000, nuclearTech: 2000 },
    durationSeconds: 120,
    rewards: [{ itemKey: 'seldonsPrimer', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  holoProjectorResearch: {
    key: 'holoProjectorResearch',
    name: 'Research Holo-Projector Tech',
    description: 'Reverse-engineer Imperial holographic technology to improve nuclear research capabilities.',
    era: Era.ReligiousDominance,
    type: 'research',
    cost: { nuclearTech: 8000, rawMaterials: 4800 },
    durationSeconds: 180,
    rewards: [{ itemKey: 'holoProjectorBlueprints', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  encyclopediaCompilation: {
    key: 'encyclopediaCompilation',
    name: 'Complete Encyclopedia Volume',
    description: 'Assemble and edit a complete volume of the Encyclopedia Galactica.',
    era: Era.ReligiousDominance,
    type: 'research',
    cost: { knowledge: 15000, influence: 5000 },
    durationSeconds: 300,
    rewards: [{ itemKey: 'encyclopediaVolume', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  dataCrystalDecryption: {
    key: 'dataCrystalDecryption',
    name: 'Decrypt Data Crystal',
    description: 'Decode the contents of a pre-Empire data crystal found in Terminus\'s vaults.',
    era: Era.ReligiousDominance,
    type: 'research',
    cost: { knowledge: 10000, nuclearTech: 5000 },
    durationSeconds: 240,
    rewards: [{ itemKey: 'ancientDataCrystal', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  sacredTextStudy: {
    key: 'sacredTextStudy',
    name: 'Annotate Sacred Texts',
    description: 'Study and annotate the texts of the technological religion for missionaries.',
    era: Era.ReligiousDominance,
    type: 'research',
    cost: { knowledge: 8000, influence: 3000 },
    durationSeconds: 150,
    rewards: [{ itemKey: 'sacredTextAnnotations', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },

  // ─── Era 0 Missions ─────────────────────────────────────────────────

  anacreonReconnaissance: {
    key: 'anacreonReconnaissance',
    name: 'Anacreon Reconnaissance',
    description: 'Send an agent to gather intelligence on Anacreon\'s military capabilities.',
    era: Era.ReligiousDominance,
    type: 'mission',
    cost: { influence: 4000, rawMaterials: 3600 },
    durationSeconds: 60,
    rewards: [{ itemKey: 'crisisCatalyst', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  diplomaticOutreach: {
    key: 'diplomaticOutreach',
    name: 'Diplomatic Outreach',
    description: 'Dispatch a diplomatic mission to a neighboring kingdom.',
    era: Era.ReligiousDominance,
    type: 'mission',
    cost: { influence: 6000, rawMaterials: 2400 },
    durationSeconds: 90,
    rewards: [{ itemKey: 'diplomaticPouch', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  reactorStressTest: {
    key: 'reactorStressTest',
    name: 'Reactor Stress Test',
    description: 'Push a nuclear reactor to its limits to develop overcharge protocols.',
    era: Era.ReligiousDominance,
    type: 'mission',
    cost: { rawMaterials: 9600, nuclearTech: 3000 },
    durationSeconds: 120,
    rewards: [{ itemKey: 'reactorOvercharge', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  missionaryExpedition: {
    key: 'missionaryExpedition',
    name: 'Missionary Expedition',
    description: 'Send missionaries to spread the religion of science to nearby worlds.',
    era: Era.ReligiousDominance,
    type: 'mission',
    cost: { influence: 5000, rawMaterials: 6000 },
    durationSeconds: 180,
    rewards: [{ itemKey: 'missionaryZeal', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  materialScavenging: {
    key: 'materialScavenging',
    name: 'Material Scavenging Run',
    description: 'Scavenge abandoned Imperial facilities on Terminus for emergency supplies.',
    era: Era.ReligiousDominance,
    type: 'mission',
    cost: { rawMaterials: 7200, influence: 2000 },
    durationSeconds: 60,
    rewards: [{ itemKey: 'emergencyReserves', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // ERA 1: TRADING EXPANSION
  // ═══════════════════════════════════════════════════════════════════════

  // ─── Era 1 Research Projects ─────────────────────────────────────────

  tradeAnalysis: {
    key: 'tradeAnalysis',
    name: 'Trade Route Analysis',
    description: 'Analyze galactic trade data to optimize merchant strategies.',
    era: Era.TradingExpansion,
    type: 'research',
    cost: { knowledge: 50000, nuclearTech: 20000 },
    durationSeconds: 300,
    rewards: [{ itemKey: 'tradersLedger', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  hyperdriveCalibration: {
    key: 'hyperdriveCalibration',
    name: 'Hyperdrive Calibration Research',
    description: 'Research improvements to hyperdrive calibration for the merchant fleet.',
    era: Era.TradingExpansion,
    type: 'research',
    cost: { nuclearTech: 80000, rawMaterials: 48000 },
    durationSeconds: 600,
    rewards: [{ itemKey: 'hyperdriveCalibrator', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  tradeRouteSurvey: {
    key: 'tradeRouteSurvey',
    name: 'Galactic Route Survey',
    description: 'Commission a comprehensive survey of new trade routes through the Periphery.',
    era: Era.TradingExpansion,
    type: 'research',
    cost: { knowledge: 150000, influence: 50000 },
    durationSeconds: 900,
    rewards: [{ itemKey: 'tradeRouteAtlas', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  korellianSmithing: {
    key: 'korellianSmithing',
    name: 'Study Korellian Smithing',
    description: 'Analyze manufacturing techniques captured from Korell.',
    era: Era.TradingExpansion,
    type: 'research',
    cost: { knowledge: 100000, rawMaterials: 96000 },
    durationSeconds: 480,
    rewards: [{ itemKey: 'korellianSmithingManual', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  merchantGuildResearch: {
    key: 'merchantGuildResearch',
    name: 'Codify Merchant Practices',
    description: 'Research and formalize the commercial practices of the Merchant Princes.',
    era: Era.TradingExpansion,
    type: 'research',
    cost: { knowledge: 80000, influence: 40000 },
    durationSeconds: 360,
    rewards: [{ itemKey: 'merchantGuildCharter', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },

  // ─── Era 1 Missions ─────────────────────────────────────────────────

  korellTradeRun: {
    key: 'korellTradeRun',
    name: 'Korell Trade Run',
    description: 'Send a merchant ship to Korell to exploit favorable market conditions.',
    era: Era.TradingExpansion,
    type: 'mission',
    cost: { rawMaterials: 60000, influence: 20000 },
    durationSeconds: 300,
    rewards: [{ itemKey: 'tradeWinds', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  blackMarketDeal: {
    key: 'blackMarketDeal',
    name: 'Black Market Acquisition',
    description: 'Acquire rare materials through unofficial channels.',
    era: Era.TradingExpansion,
    type: 'mission',
    cost: { influence: 80000, rawMaterials: 36000 },
    durationSeconds: 240,
    rewards: [{ itemKey: 'smugglersCache', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  marketCorner: {
    key: 'marketCorner',
    name: 'Corner the Market',
    description: 'Execute an aggressive trading strategy to dominate a sector.',
    era: Era.TradingExpansion,
    type: 'mission',
    cost: { influence: 100000, rawMaterials: 60000 },
    durationSeconds: 600,
    rewards: [{ itemKey: 'marketManipulation', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  techDemonstration: {
    key: 'techDemonstration',
    name: 'Technology Demonstration',
    description: 'Showcase Foundation technology to impress potential trading partners.',
    era: Era.TradingExpansion,
    type: 'mission',
    cost: { nuclearTech: 60000, rawMaterials: 48000 },
    durationSeconds: 180,
    rewards: [{ itemKey: 'technologicalSample', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  politicalNegotiation: {
    key: 'politicalNegotiation',
    name: 'Political Negotiation',
    description: 'Negotiate favorable terms with a Periphery world leader.',
    era: Era.TradingExpansion,
    type: 'mission',
    cost: { influence: 120000, rawMaterials: 36000 },
    durationSeconds: 420,
    rewards: [{ itemKey: 'diplomaticLeverage', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // ERA 2: PSYCHOLOGICAL INFLUENCE
  // ═══════════════════════════════════════════════════════════════════════

  // ─── Era 2 Research Projects ─────────────────────────────────────────

  mentalicsStudy: {
    key: 'mentalicsStudy',
    name: 'Mentalics Training Program',
    description: 'Develop a curriculum for training mentalic abilities based on Second Foundation techniques.',
    era: Era.PsychologicalInfluence,
    type: 'research',
    cost: { knowledge: 500000, influence: 200000 },
    durationSeconds: 1200,
    rewards: [{ itemKey: 'mentalicsTrainingGuide', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  psychohistoryAdvancement: {
    key: 'psychohistoryAdvancement',
    name: 'Advance Psychohistory',
    description: 'Push the boundaries of psychohistorical mathematics with new predictive models.',
    era: Era.PsychologicalInfluence,
    type: 'research',
    cost: { knowledge: 800000, nuclearTech: 300000 },
    durationSeconds: 1800,
    rewards: [{ itemKey: 'psychohistoryRefinement', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  secondFoundationResearch: {
    key: 'secondFoundationResearch',
    name: 'Second Foundation Archives Study',
    description: 'Study recovered archives from the Second Foundation\'s hidden base.',
    era: Era.PsychologicalInfluence,
    type: 'research',
    cost: { knowledge: 1500000, influence: 500000 },
    durationSeconds: 3600,
    rewards: [{ itemKey: 'secondFoundationArchives', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  emotionalControlResearch: {
    key: 'emotionalControlResearch',
    name: 'Emotional Control Analysis',
    description: 'Analyze the Mule\'s methods of emotional manipulation for defensive applications.',
    era: Era.PsychologicalInfluence,
    type: 'research',
    cost: { knowledge: 1000000, influence: 400000 },
    durationSeconds: 2400,
    rewards: [{ itemKey: 'emotionalControlDevice', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  convergenceResearch: {
    key: 'convergenceResearch',
    name: 'Convergence Field Research',
    description: 'Research the application of mentalic fields to industrial processes.',
    era: Era.PsychologicalInfluence,
    type: 'research',
    cost: { nuclearTech: 800000, rawMaterials: 720000 },
    durationSeconds: 1500,
    rewards: [{ itemKey: 'convergenceLens', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },

  // ─── Era 2 Missions ─────────────────────────────────────────────────

  mentalShieldDeployment: {
    key: 'mentalShieldDeployment',
    name: 'Deploy Mental Shields',
    description: 'Deploy psychic shielding technology across the Foundation\'s key installations.',
    era: Era.PsychologicalInfluence,
    type: 'mission',
    cost: { influence: 600000, rawMaterials: 480000 },
    durationSeconds: 900,
    rewards: [{ itemKey: 'mentalShield', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  muleInvestigation: {
    key: 'muleInvestigation',
    name: 'Investigate Mule\'s Legacy',
    description: 'Search the Mule\'s former territories for remnants of his psychic power.',
    era: Era.PsychologicalInfluence,
    type: 'mission',
    cost: { influence: 800000, rawMaterials: 360000 },
    durationSeconds: 1200,
    rewards: [{ itemKey: 'muleSEcho', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  subliminalCampaign: {
    key: 'subliminalCampaign',
    name: 'Subliminal Campaign',
    description: 'Launch a subtle mentalic influence campaign across multiple worlds.',
    era: Era.PsychologicalInfluence,
    type: 'mission',
    cost: { influence: 1000000, rawMaterials: 600000 },
    durationSeconds: 1800,
    rewards: [{ itemKey: 'subliminalBroadcast', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  psychicResonanceMission: {
    key: 'psychicResonanceMission',
    name: 'Psychic Resonance Experiment',
    description: 'Conduct a large-scale experiment in collective consciousness.',
    era: Era.PsychologicalInfluence,
    type: 'mission',
    cost: { rawMaterials: 960000, nuclearTech: 400000 },
    durationSeconds: 1500,
    rewards: [{ itemKey: 'psychicResonance', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  propagandaBlitz: {
    key: 'propagandaBlitz',
    name: 'Propaganda Blitz',
    description: 'Coordinate a massive information campaign to sway public opinion across the galaxy.',
    era: Era.PsychologicalInfluence,
    type: 'mission',
    cost: { influence: 1200000, rawMaterials: 720000 },
    durationSeconds: 600,
    rewards: [{ itemKey: 'foundationPropaganda', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // ERA 3: GALACTIC REUNIFICATION
  // ═══════════════════════════════════════════════════════════════════════

  // ─── Era 3 Research Projects ─────────────────────────────────────────

  gaianPhilosophy: {
    key: 'gaianPhilosophy',
    name: 'Study Gaian Philosophy',
    description: 'Research the philosophical underpinnings of Gaia\'s planetary consciousness.',
    era: Era.GalacticReunification,
    type: 'research',
    cost: { knowledge: 5000000, influence: 2000000 },
    durationSeconds: 3600,
    rewards: [{ itemKey: 'gaianHarmonyManual', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  earthArcheology: {
    key: 'earthArcheology',
    name: 'Earth Archeological Survey',
    description: 'Fund an expedition to rediscover and catalog Earth\'s hidden treasures.',
    era: Era.GalacticReunification,
    type: 'research',
    cost: { knowledge: 10000000, rawMaterials: 6000000 },
    durationSeconds: 7200,
    rewards: [{ itemKey: 'earthsLegacy', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  zerothLawAnalysis: {
    key: 'zerothLawAnalysis',
    name: 'Zeroth Law Analysis',
    description: 'Study Daneel Olivaw\'s Zeroth Law of Robotics and its implications for galactic governance.',
    era: Era.GalacticReunification,
    type: 'research',
    cost: { knowledge: 20000000, influence: 10000000 },
    durationSeconds: 5400,
    rewards: [{ itemKey: 'zerothLawCodex', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  galaxiaModeling: {
    key: 'galaxiaModeling',
    name: 'Model Galaxia',
    description: 'Create mathematical models of how a galaxy-wide consciousness might function.',
    era: Era.GalacticReunification,
    type: 'research',
    cost: { knowledge: 30000000, nuclearTech: 15000000 },
    durationSeconds: 6000,
    rewards: [{ itemKey: 'galaxiaBlueprint', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },
  graviticResearch: {
    key: 'graviticResearch',
    name: 'Gravitic Technology Research',
    description: 'Reverse-engineer the gravitic technology of advanced civilizations.',
    era: Era.GalacticReunification,
    type: 'research',
    cost: { nuclearTech: 20000000, rawMaterials: 18000000 },
    durationSeconds: 4800,
    rewards: [{ itemKey: 'graviticConverterSpecs', quantity: 1 }],
    repeatable: true,
    maxCompletions: 10,
  },

  // ─── Era 3 Missions ─────────────────────────────────────────────────

  galaxiaOutreach: {
    key: 'galaxiaOutreach',
    name: 'Galaxia Outreach Wave',
    description: 'Broadcast a wave of unified consciousness to accelerate the Galaxia project.',
    era: Era.GalacticReunification,
    type: 'mission',
    cost: { influence: 10000000, rawMaterials: 6000000 },
    durationSeconds: 3600,
    rewards: [{ itemKey: 'galaxiaWave', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  graviticExperiment: {
    key: 'graviticExperiment',
    name: 'Gravitic Power Experiment',
    description: 'Conduct a dangerous experiment with gravitic technology to unlock new capabilities.',
    era: Era.GalacticReunification,
    type: 'mission',
    cost: { nuclearTech: 20000000, rawMaterials: 12000000 },
    durationSeconds: 2400,
    rewards: [{ itemKey: 'graviticSurge', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  temporalStudy: {
    key: 'temporalStudy',
    name: 'Temporal Acceleration Test',
    description: 'Test experimental temporal acceleration technology on a controlled research project.',
    era: Era.GalacticReunification,
    type: 'mission',
    cost: { rawMaterials: 36000000, nuclearTech: 15000000 },
    durationSeconds: 4200,
    rewards: [{ itemKey: 'temporalAccelerator', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  planetaryMeldMission: {
    key: 'planetaryMeldMission',
    name: 'Planetary Meld Expedition',
    description: 'Send an expedition to Gaia to experience and learn from the planetary consciousness.',
    era: Era.GalacticReunification,
    type: 'mission',
    cost: { influence: 20000000, rawMaterials: 24000000 },
    durationSeconds: 5400,
    rewards: [{ itemKey: 'planetaryMeld', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
  unificationSummit: {
    key: 'unificationSummit',
    name: 'Galactic Unification Summit',
    description: 'Organize a summit of galactic leaders to advance the cause of reunification.',
    era: Era.GalacticReunification,
    type: 'mission',
    cost: { influence: 50000000, rawMaterials: 12000000 },
    durationSeconds: 7200,
    rewards: [{ itemKey: 'unificationDecree', quantity: 1 }],
    repeatable: true,
    maxCompletions: null,
  },
};

export const ALL_ACTIVITY_KEYS = Object.keys(ACTIVITY_DEFINITIONS);
