import { BuildingDefinition, BuildingKey } from '../types/buildings.js';
import { Era } from '../types/eras.js';

export const BUILDING_DEFINITIONS: Record<BuildingKey, BuildingDefinition> = {
  // ═══════════════════════════════════════════════════════════════════════
  // Era 0: Religious Dominance (14 buildings)
  // ═══════════════════════════════════════════════════════════════════════

  survivalShelter: {
    key: 'survivalShelter',
    name: 'Survival Shelter',
    description: 'A crude but functional shelter on Terminus. The first step of survival on the galaxy\'s edge.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 10 },
    production: [
      { resource: 'credits', amount: 0.2 },
      { resource: 'rawMaterials', amount: 0.1 },
    ],
    costMultiplier: 1.15,
  },
  waterReclamator: {
    key: 'waterReclamator',
    name: 'Water Reclamator',
    description: 'Recycling atmospheric moisture into drinkable water. Essential for colony survival.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 25, rawMaterials: 8 },
    production: [
      { resource: 'rawMaterials', amount: 0.3 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'survivalShelter', count: 3 } },
  },
  hydroponicsFarm: {
    key: 'hydroponicsFarm',
    name: 'Hydroponics Farm',
    description: 'Growing food in controlled environments. Terminus\'s soil won\'t feed the colony alone.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 60, rawMaterials: 15 },
    production: [
      { resource: 'credits', amount: 0.3 },
      { resource: 'rawMaterials', amount: 0.2 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'survivalShelter', count: 3 } },
  },
  miningOutpost: {
    key: 'miningOutpost',
    name: 'Mining Outpost',
    description: 'Open-cast excavations on Terminus, pulling ore from the planet\'s crust.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 150, rawMaterials: 10 },
    production: [
      { resource: 'rawMaterials', amount: 0.8 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'survivalShelter', count: 5 } },
  },
  solarArray: {
    key: 'solarArray',
    name: 'Solar Array',
    description: 'Photovoltaic collectors powering the colony\'s first electrical grid.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 400, rawMaterials: 20 },
    production: [
      { resource: 'nuclearTech', amount: 0.1 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'waterReclamator', count: 3 } },
  },
  researchStation: {
    key: 'researchStation',
    name: 'Research Station',
    description: 'Scientists cataloguing human knowledge for the Encyclopedia Galactica.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 1000, rawMaterials: 30 },
    production: [
      { resource: 'knowledge', amount: 0.5 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'hydroponicsFarm', count: 3 } },
  },
  steelFoundry: {
    key: 'steelFoundry',
    name: 'Steel Foundry',
    description: 'Smelting Terminus ore into construction-grade alloys.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 2500, rawMaterials: 80 },
    production: [
      { resource: 'credits', amount: 1 },
      { resource: 'rawMaterials', amount: 1.5 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'miningOutpost', count: 5 } },
  },
  nuclearReactor: {
    key: 'nuclearReactor',
    name: 'Nuclear Reactor',
    description: 'Atomic reactors that power the Foundation and awe the neighboring kingdoms.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 6000, rawMaterials: 100 },
    production: [
      { resource: 'nuclearTech', amount: 0.5 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'solarArray', count: 5 } },
  },
  encyclopediaArchive: {
    key: 'encyclopediaArchive',
    name: 'Encyclopedia Archive',
    description: 'The great halls where scholars compile humanity\'s accumulated wisdom.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 15000, knowledge: 100, rawMaterials: 50 },
    production: [
      { resource: 'knowledge', amount: 3 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'researchStation', count: 5 } },
  },
  fabricationShop: {
    key: 'fabricationShop',
    name: 'Fabrication Shop',
    description: 'Assembly lines producing gadgets the Four Kingdoms can\'t replicate.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 40000, rawMaterials: 300 },
    production: [
      { resource: 'credits', amount: 8 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'steelFoundry', count: 5 } },
  },
  missionaryChapel: {
    key: 'missionaryChapel',
    name: 'Missionary Chapel',
    description: 'Technician-priests spreading the holy word of atomic power to the Four Kingdoms.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 100000, knowledge: 300, rawMaterials: 200 },
    production: [
      { resource: 'influence', amount: 2 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'encyclopediaArchive', count: 3 } },
  },
  holoTemple: {
    key: 'holoTemple',
    name: 'Holo-Temple',
    description: 'Grand cathedrals where nuclear technology is presented as divine miracle.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 200000, influence: 100, rawMaterials: 500 },
    production: [
      { resource: 'influence', amount: 5 },
      { resource: 'credits', amount: 6 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'missionaryChapel', count: 5 } },
  },
  atomicForge: {
    key: 'atomicForge',
    name: 'Atomic Forge',
    description: 'Nuclear-powered fabricators that transmute raw elements into precision components.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 350000, nuclearTech: 200, rawMaterials: 1000 },
    production: [
      { resource: 'nuclearTech', amount: 3 },
      { resource: 'rawMaterials', amount: 4 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'nuclearReactor', count: 5 } },
  },
  cathedralOfScience: {
    key: 'cathedralOfScience',
    name: 'Cathedral of Science',
    description: 'The Foundation\'s crown jewel \u2014 a fortress of all human understanding.',
    era: Era.ReligiousDominance,
    baseCost: { credits: 500000, knowledge: 500, nuclearTech: 200, influence: 200, rawMaterials: 1500 },
    production: [
      { resource: 'credits', amount: 15 },
      { resource: 'knowledge', amount: 4 },
      { resource: 'influence', amount: 3 },
      { resource: 'nuclearTech', amount: 2 },
      { resource: 'rawMaterials', amount: 1 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'holoTemple', count: 5 } },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Era 1: Trading Expansion (14 buildings)
  // ═══════════════════════════════════════════════════════════════════════

  tradingPost: {
    key: 'tradingPost',
    name: 'Trading Post',
    description: 'A frontier outpost where Foundation goods flow to hungry border worlds.',
    era: Era.TradingExpansion,
    baseCost: { credits: 500000, rawMaterials: 5000 },
    production: [
      { resource: 'credits', amount: 25 },
      { resource: 'rawMaterials', amount: 2 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { era: Era.TradingExpansion },
  },
  manufacturingPlant: {
    key: 'manufacturingPlant',
    name: 'Manufacturing Plant',
    description: 'Mass-producing Foundation technology for export across the Periphery.',
    era: Era.TradingExpansion,
    baseCost: { credits: 1000000, rawMaterials: 20000 },
    production: [
      { resource: 'credits', amount: 40 },
      { resource: 'rawMaterials', amount: 5 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'tradingPost', count: 3 } },
  },
  cargoWarehouse: {
    key: 'cargoWarehouse',
    name: 'Cargo Warehouse',
    description: 'Vast stockpiles at hyperspace junction points, ready for redistribution.',
    era: Era.TradingExpansion,
    baseCost: { credits: 2000000, rawMaterials: 30000 },
    production: [
      { resource: 'rawMaterials', amount: 20 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'tradingPost', count: 3 } },
  },
  foundationBank: {
    key: 'foundationBank',
    name: 'Foundation Bank',
    description: 'Lending credits at interest to planetary governments. The invisible chain.',
    era: Era.TradingExpansion,
    baseCost: { credits: 4000000, knowledge: 20000, rawMaterials: 5000 },
    production: [
      { resource: 'credits', amount: 80 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'tradingPost', count: 5 } },
  },
  orbitalShipyard: {
    key: 'orbitalShipyard',
    name: 'Orbital Shipyard',
    description: 'Orbital construction yards assembling the Foundation\'s merchant fleet.',
    era: Era.TradingExpansion,
    baseCost: { credits: 7500000, rawMaterials: 50000 },
    production: [
      { resource: 'credits', amount: 50 },
      { resource: 'nuclearTech', amount: 8 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'manufacturingPlant', count: 5 } },
  },
  commodityExchange: {
    key: 'commodityExchange',
    name: 'Commodity Exchange',
    description: 'The marketplace where Foundation traders set prices for half the Periphery.',
    era: Era.TradingExpansion,
    baseCost: { credits: 15000000, rawMaterials: 40000 },
    production: [
      { resource: 'credits', amount: 100 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'cargoWarehouse', count: 5 } },
  },
  refineryComplex: {
    key: 'refineryComplex',
    name: 'Refinery Complex',
    description: 'Orbital platforms refining raw ore into trade-grade alloys and fuels.',
    era: Era.TradingExpansion,
    baseCost: { credits: 30000000, rawMaterials: 80000 },
    production: [
      { resource: 'rawMaterials', amount: 30 },
      { resource: 'nuclearTech', amount: 10 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'manufacturingPlant', count: 5 } },
  },
  merchantGuildHall: {
    key: 'merchantGuildHall',
    name: 'Merchant Guild Hall',
    description: 'The nerve center of the Foundation\'s commercial empire.',
    era: Era.TradingExpansion,
    baseCost: { credits: 50000000, influence: 30000, rawMaterials: 50000 },
    production: [
      { resource: 'credits', amount: 150 },
      { resource: 'influence', amount: 12 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'foundationBank', count: 5 } },
  },
  navigatorsAcademy: {
    key: 'navigatorsAcademy',
    name: 'Navigators Academy',
    description: 'An academy of hyperspace navigators charting the fastest trade routes.',
    era: Era.TradingExpansion,
    baseCost: { credits: 80000000, knowledge: 50000, rawMaterials: 30000 },
    production: [
      { resource: 'knowledge', amount: 25 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'orbitalShipyard', count: 5 } },
  },
  tradeEmbassy: {
    key: 'tradeEmbassy',
    name: 'Trade Embassy',
    description: 'Diplomatic missions converting economic leverage into political power.',
    era: Era.TradingExpansion,
    baseCost: { credits: 120000000, influence: 50000, rawMaterials: 40000 },
    production: [
      { resource: 'influence', amount: 20 },
      { resource: 'credits', amount: 80 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'merchantGuildHall', count: 5 } },
  },
  weaponsFactory: {
    key: 'weaponsFactory',
    name: 'Weapons Factory',
    description: 'Armaments for sale \u2014 because even pacifists must arm their clients.',
    era: Era.TradingExpansion,
    baseCost: { credits: 180000000, nuclearTech: 100000, rawMaterials: 100000 },
    production: [
      { resource: 'nuclearTech', amount: 25 },
      { resource: 'credits', amount: 100 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'refineryComplex', count: 5 } },
  },
  freighterDocks: {
    key: 'freighterDocks',
    name: 'Freighter Docks',
    description: 'Deep-space staging where hundreds of trade ships dock simultaneously.',
    era: Era.TradingExpansion,
    baseCost: { credits: 280000000, rawMaterials: 150000 },
    production: [
      { resource: 'credits', amount: 200 },
      { resource: 'rawMaterials', amount: 20 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'orbitalShipyard', count: 5 } },
  },
  mallowTradingHouse: {
    key: 'mallowTradingHouse',
    name: 'Mallow Trading House',
    description: 'Named for the greatest Merchant Prince. Profit above all.',
    era: Era.TradingExpansion,
    baseCost: { credits: 400000000, influence: 100000, rawMaterials: 100000 },
    production: [
      { resource: 'credits', amount: 500 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'tradeEmbassy', count: 5 } },
  },
  galacticBourse: {
    key: 'galacticBourse',
    name: 'Galactic Bourse',
    description: 'The central exchange where planetary economies are made or broken.',
    era: Era.TradingExpansion,
    baseCost: { credits: 500000000, influence: 150000, knowledge: 100000, nuclearTech: 50000, rawMaterials: 80000 },
    production: [
      { resource: 'credits', amount: 400 },
      { resource: 'rawMaterials', amount: 20 },
      { resource: 'nuclearTech', amount: 15 },
      { resource: 'influence', amount: 15 },
      { resource: 'knowledge', amount: 10 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'mallowTradingHouse', count: 5 } },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Era 2: Psychological Influence (14 buildings)
  // ═══════════════════════════════════════════════════════════════════════

  psychohistoryLab: {
    key: 'psychohistoryLab',
    name: 'Psychohistory Lab',
    description: 'Where mathematicians model the future of thirty trillion souls.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 100000000, knowledge: 500000, rawMaterials: 200000 },
    production: [
      { resource: 'knowledge', amount: 100 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { era: Era.PsychologicalInfluence },
  },
  emotionalAdjustmentCenter: {
    key: 'emotionalAdjustmentCenter',
    name: 'Emotional Adjustment Center',
    description: 'Subtle facilities where mentalics fine-tune the emotional states of key individuals.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 200000000, influence: 100000, rawMaterials: 300000 },
    production: [
      { resource: 'influence', amount: 50 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'psychohistoryLab', count: 3 } },
  },
  mentalicsAcademy: {
    key: 'mentalicsAcademy',
    name: 'Mentalics Academy',
    description: 'The training ground for the Second Foundation\'s psychic elite.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 400000000, influence: 200000, rawMaterials: 400000 },
    production: [
      { resource: 'knowledge', amount: 80 },
      { resource: 'influence', amount: 30 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'psychohistoryLab', count: 3 } },
  },
  auraManufactory: {
    key: 'auraManufactory',
    name: 'Aura Manufactory',
    description: 'Devices that project an aura of authority and trust around the wearer.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 800000000, influence: 400000, rawMaterials: 800000 },
    production: [
      { resource: 'influence', amount: 80 },
      { resource: 'credits', amount: 1000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'emotionalAdjustmentCenter', count: 5 } },
  },
  primeRadiantVault: {
    key: 'primeRadiantVault',
    name: 'Prime Radiant Vault',
    description: 'The sacred device that displays the Seldon Plan in all its mathematical beauty.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 1500000000, knowledge: 1000000, rawMaterials: 500000 },
    production: [
      { resource: 'knowledge', amount: 300 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'mentalicsAcademy', count: 5 } },
  },
  propagandaNetwork: {
    key: 'propagandaNetwork',
    name: 'Propaganda Network',
    description: 'Subtly shaping public opinion across worlds that don\'t know they\'re being guided.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 3000000000, influence: 800000, rawMaterials: 300000 },
    production: [
      { resource: 'influence', amount: 150 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'auraManufactory', count: 5 } },
  },
  dreamProbeLab: {
    key: 'dreamProbeLab',
    name: 'Dream Probe Lab',
    description: 'Mentalic researchers explore the subconscious for patterns invisible to mathematics.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 5000000000, influence: 500000, knowledge: 500000, rawMaterials: 500000 },
    production: [
      { resource: 'knowledge', amount: 200 },
      { resource: 'influence', amount: 100 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'primeRadiantVault', count: 5 } },
  },
  imperialArchive: {
    key: 'imperialArchive',
    name: 'Imperial Archive',
    description: 'Salvaged records of the fallen Galactic Empire \u2014 twelve millennia of data.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 10000000000, knowledge: 2000000, rawMaterials: 1000000 },
    production: [
      { resource: 'knowledge', amount: 600 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'dreamProbeLab', count: 5 } },
  },
  shieldGenerator: {
    key: 'shieldGenerator',
    name: 'Shield Generator',
    description: 'Planetary defense screens powered by psychohistorical prediction of attack vectors.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 15000000000, nuclearTech: 1000000, rawMaterials: 2000000 },
    production: [
      { resource: 'nuclearTech', amount: 200 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'propagandaNetwork', count: 5 } },
  },
  conversionChamber: {
    key: 'conversionChamber',
    name: 'Conversion Chamber',
    description: 'Reverse-engineered from the Mule\'s techniques. Persuasion beyond resistance.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 25000000000, influence: 2000000, rawMaterials: 3000000 },
    production: [
      { resource: 'influence', amount: 500 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'shieldGenerator', count: 5 } },
  },
  speakersSanctum: {
    key: 'speakersSanctum',
    name: 'Speakers\' Sanctum',
    description: 'The inner circle of the Second Foundation \u2014 Speakers who guide the Plan.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 40000000000, influence: 3000000, knowledge: 2000000, rawMaterials: 2000000 },
    production: [
      { resource: 'knowledge', amount: 400 },
      { resource: 'influence', amount: 300 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'imperialArchive', count: 5 } },
  },
  mindShieldArray: {
    key: 'mindShieldArray',
    name: 'Mind Shield Array',
    description: 'Defensive networks that protect against mentalic intrusion \u2014 built after the Mule.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 60000000000, nuclearTech: 3000000, influence: 1000000, rawMaterials: 4000000 },
    production: [
      { resource: 'nuclearTech', amount: 300 },
      { resource: 'influence', amount: 200 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'conversionChamber', count: 5 } },
  },
  whisperShipHangar: {
    key: 'whisperShipHangar',
    name: 'Whisper Ship Hangar',
    description: 'Covert hangars for the Second Foundation\'s psychological influence vessels.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 80000000000, influence: 4000000, nuclearTech: 2000000, rawMaterials: 5000000 },
    production: [
      { resource: 'influence', amount: 400 },
      { resource: 'nuclearTech', amount: 150 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'speakersSanctum', count: 5 } },
  },
  secondFoundationRetreat: {
    key: 'secondFoundationRetreat',
    name: 'Second Foundation Retreat',
    description: 'Star\'s End \u2014 the hidden world where the true guardians of the Plan reside.',
    era: Era.PsychologicalInfluence,
    baseCost: { credits: 100000000000, knowledge: 5000000, influence: 5000000, nuclearTech: 2000000, rawMaterials: 5000000 },
    production: [
      { resource: 'credits', amount: 10000 },
      { resource: 'knowledge', amount: 500 },
      { resource: 'influence', amount: 400 },
      { resource: 'nuclearTech', amount: 200 },
      { resource: 'rawMaterials', amount: 100 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'whisperShipHangar', count: 5 } },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Era 3: Galactic Reunification (14 buildings)
  // ═══════════════════════════════════════════════════════════════════════

  graviticPlant: {
    key: 'graviticPlant',
    name: 'Gravitic Plant',
    description: 'Anti-gravity technology that rewrites the rules of engineering and transport.',
    era: Era.GalacticReunification,
    baseCost: { credits: 10000000000, nuclearTech: 5000000, rawMaterials: 3000000 },
    production: [
      { resource: 'nuclearTech', amount: 1000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { era: Era.GalacticReunification },
  },
  gaianBiosphere: {
    key: 'gaianBiosphere',
    name: 'Gaian Biosphere',
    description: 'A self-sustaining ecosystem where every lifeform shares one consciousness.',
    era: Era.GalacticReunification,
    baseCost: { credits: 20000000000, influence: 5000000, rawMaterials: 5000000 },
    production: [
      { resource: 'rawMaterials', amount: 1000 },
      { resource: 'knowledge', amount: 500 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'graviticPlant', count: 3 } },
  },
  graviticFoundry: {
    key: 'graviticFoundry',
    name: 'Gravitic Foundry',
    description: 'Manufacturing bays where alloys are shaped by controlled gravity fields.',
    era: Era.GalacticReunification,
    baseCost: { credits: 40000000000, nuclearTech: 10000000, rawMaterials: 5000000 },
    production: [
      { resource: 'nuclearTech', amount: 2000 },
      { resource: 'rawMaterials', amount: 1500 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'graviticPlant', count: 3 } },
  },
  consciousnessAmplifier: {
    key: 'consciousnessAmplifier',
    name: 'Consciousness Amplifier',
    description: 'Technology that extends the Gaian gestalt across interstellar distances.',
    era: Era.GalacticReunification,
    baseCost: { credits: 80000000000, influence: 20000000, knowledge: 10000000, rawMaterials: 5000000 },
    production: [
      { resource: 'influence', amount: 2000 },
      { resource: 'knowledge', amount: 1500 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'gaianBiosphere', count: 5 } },
  },
  terraformingEngine: {
    key: 'terraformingEngine',
    name: 'Terraforming Engine',
    description: 'Reshaping barren worlds into habitable paradises using gravitic manipulation.',
    era: Era.GalacticReunification,
    baseCost: { credits: 150000000000, rawMaterials: 30000000, nuclearTech: 10000000 },
    production: [
      { resource: 'rawMaterials', amount: 5000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'graviticFoundry', count: 5 } },
  },
  galaxiaBeacon: {
    key: 'galaxiaBeacon',
    name: 'Galaxia Beacon',
    description: 'Transmitters that carry the Galaxia signal to the farthest spiral arms.',
    era: Era.GalacticReunification,
    baseCost: { credits: 300000000000, influence: 50000000, knowledge: 30000000, rawMaterials: 20000000 },
    production: [
      { resource: 'influence', amount: 5000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'consciousnessAmplifier', count: 5 } },
  },
  stellarHarvester: {
    key: 'stellarHarvester',
    name: 'Stellar Harvester',
    description: 'Drawing energy directly from stars to power the great works of reunification.',
    era: Era.GalacticReunification,
    baseCost: { credits: 600000000000, nuclearTech: 50000000, rawMaterials: 30000000 },
    production: [
      { resource: 'nuclearTech', amount: 5000 },
      { resource: 'credits', amount: 50000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'terraformingEngine', count: 5 } },
  },
  robotArchives: {
    key: 'robotArchives',
    name: 'Robot Archives',
    description: 'The hidden records of R. Daneel Olivaw \u2014 twenty thousand years of guidance.',
    era: Era.GalacticReunification,
    baseCost: { credits: 1000000000000, knowledge: 100000000, rawMaterials: 30000000 },
    production: [
      { resource: 'knowledge', amount: 8000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'galaxiaBeacon', count: 5 } },
  },
  wormholeNexus: {
    key: 'wormholeNexus',
    name: 'Wormhole Nexus',
    description: 'Stabilized passages through hyperspace. Instant travel between any two points.',
    era: Era.GalacticReunification,
    baseCost: { credits: 1500000000000, nuclearTech: 100000000, rawMaterials: 50000000 },
    production: [
      { resource: 'credits', amount: 100000 },
      { resource: 'influence', amount: 3000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'stellarHarvester', count: 5 } },
  },
  galacticSenate: {
    key: 'galacticSenate',
    name: 'Galactic Senate',
    description: 'Where every world has a voice, and every voice is heard through shared consciousness.',
    era: Era.GalacticReunification,
    baseCost: { credits: 2500000000000, influence: 200000000, knowledge: 100000000, rawMaterials: 50000000 },
    production: [
      { resource: 'influence', amount: 8000 },
      { resource: 'credits', amount: 80000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'robotArchives', count: 5 } },
  },
  singularityForge: {
    key: 'singularityForge',
    name: 'Singularity Forge',
    description: 'Harnessing the edge of black holes to create materials that shouldn\'t exist.',
    era: Era.GalacticReunification,
    baseCost: { credits: 4000000000000, nuclearTech: 300000000, rawMaterials: 150000000, knowledge: 50000000, influence: 50000000 },
    production: [
      { resource: 'credits', amount: 200000 },
      { resource: 'nuclearTech', amount: 10000 },
      { resource: 'rawMaterials', amount: 8000 },
      { resource: 'knowledge', amount: 5000 },
      { resource: 'influence', amount: 3000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'wormholeNexus', count: 5 } },
  },
  galaxiaCore: {
    key: 'galaxiaCore',
    name: 'Galaxia Core',
    description: 'The beating heart of the galactic superorganism. Every mind, one mind.',
    era: Era.GalacticReunification,
    baseCost: { credits: 6000000000000, influence: 500000000, knowledge: 300000000, nuclearTech: 100000000, rawMaterials: 100000000 },
    production: [
      { resource: 'credits', amount: 500000 },
      { resource: 'knowledge', amount: 15000 },
      { resource: 'influence', amount: 12000 },
      { resource: 'nuclearTech', amount: 8000 },
      { resource: 'rawMaterials', amount: 5000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'galacticSenate', count: 5 } },
  },
  foundationHeadquarters: {
    key: 'foundationHeadquarters',
    name: 'Foundation Headquarters',
    description: 'The culmination of the Seldon Plan. Humanity, united and ascendant.',
    era: Era.GalacticReunification,
    baseCost: { credits: 8000000000000, nuclearTech: 500000000, knowledge: 500000000, influence: 500000000, rawMaterials: 300000000 },
    production: [
      { resource: 'credits', amount: 1000000 },
      { resource: 'knowledge', amount: 30000 },
      { resource: 'influence', amount: 25000 },
      { resource: 'nuclearTech', amount: 15000 },
      { resource: 'rawMaterials', amount: 10000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'singularityForge', count: 5 } },
  },
  eternityEngine: {
    key: 'eternityEngine',
    name: 'Eternity Engine',
    description: 'Beyond the Plan. Beyond the galaxy. The infinite future begins here.',
    era: Era.GalacticReunification,
    baseCost: { credits: 10000000000000, nuclearTech: 1000000000, knowledge: 1000000000, influence: 1000000000, rawMaterials: 1000000000 },
    production: [
      { resource: 'credits', amount: 5000000 },
      { resource: 'knowledge', amount: 100000 },
      { resource: 'influence', amount: 100000 },
      { resource: 'nuclearTech', amount: 50000 },
      { resource: 'rawMaterials', amount: 30000 },
    ],
    costMultiplier: 1.15,
    unlockRequirement: { building: { key: 'galaxiaCore', count: 5 } },
  },
};

export const ALL_BUILDING_KEYS = Object.keys(BUILDING_DEFINITIONS) as BuildingKey[];
