import { Era } from '../types/eras.js';
import { HeroDefinition } from '../types/heroes.js';

export const HERO_DEFINITIONS: Record<string, HeroDefinition> = {
  // ─── Era 0: Religious Dominance ──────────────────────────────────────

  hariSeldon: {
    key: 'hariSeldon',
    name: 'Hari Seldon',
    title: 'Father of Psychohistory',
    description: 'The mathematician who foresaw the fall of the Galactic Empire and created the Seldon Plan to shorten thirty thousand years of darkness to a single millennium.',
    era: Era.ReligiousDominance,
    specialization: 'research',
    durationBonus: 0.80,
  },
  salvorHardin: {
    key: 'salvorHardin',
    name: 'Salvor Hardin',
    title: 'Mayor of Terminus',
    description: 'The first Mayor of Terminus City. A master politician who saved the Foundation through cunning diplomacy and the strategic use of technological religion.',
    era: Era.ReligiousDominance,
    specialization: 'mission',
    durationBonus: 0.85,
  },
  polyVerisof: {
    key: 'polyVerisof',
    name: 'Poly Verisof',
    title: 'High Priest of Science',
    description: 'Chief missionary to Anacreon and leader of the technological religion. His reports on the Outer Kingdoms proved invaluable to Foundation strategy.',
    era: Era.ReligiousDominance,
    specialization: 'research',
    durationBonus: 0.85,
  },
  lewisPirenne: {
    key: 'lewisPirenne',
    name: 'Lewis Pirenne',
    title: 'Chairman of the Board',
    description: 'Head of the Board of Encyclopedists. Though his devotion to the Encyclopedia blinded him to political realities, his scholarly rigor advanced Foundation knowledge.',
    era: Era.ReligiousDominance,
    specialization: 'research',
    durationBonus: 0.85,
  },
  theoAporat: {
    key: 'theoAporat',
    name: 'Theo Aporat',
    title: 'Defecting Priest',
    description: 'An Anacreonese priest who saw through the religious facade and defected to the Foundation, bringing vital intelligence about the Outer Kingdoms.',
    era: Era.ReligiousDominance,
    specialization: 'mission',
    durationBonus: 0.85,
  },
  gaalDornick: {
    key: 'gaalDornick',
    name: 'Gaal Dornick',
    title: 'The First Witness',
    description: 'A young mathematician from Synnax who witnessed the trial of Hari Seldon and became the first chronicler of the Foundation. His keen observations preserved crucial early history.',
    era: Era.ReligiousDominance,
    specialization: 'research',
    durationBonus: 0.75,
  },
  emperorCleon: {
    key: 'emperorCleon',
    name: 'Emperor Cleon I',
    title: 'The Last Enlightened Emperor',
    description: 'The final Emperor who understood the Empire\'s decline. His decision to allow the Foundation\'s creation on Terminus shaped the course of galactic history.',
    era: Era.ReligiousDominance,
    specialization: 'mission',
    durationBonus: 0.75,
  },

  // ─── Era 1: Trading Expansion ────────────────────────────────────────

  hoberMallow: {
    key: 'hoberMallow',
    name: 'Hober Mallow',
    title: 'Master Trader',
    description: 'The first of the Foundation Merchant Princes. His trial and subsequent trade mission to Korell transformed Foundation foreign policy from religion to commerce.',
    era: Era.TradingExpansion,
    specialization: 'mission',
    durationBonus: 0.85,
  },
  limmarPonyets: {
    key: 'limmarPonyets',
    name: 'Limmar Ponyets',
    title: 'Rogue Trader',
    description: 'A resourceful trader who opened commerce with Askone through creative dealing and a touch of scientific showmanship.',
    era: Era.TradingExpansion,
    specialization: 'mission',
    durationBonus: 0.85,
  },
  sennettForell: {
    key: 'sennettForell',
    name: 'Sennett Forell',
    title: 'Trade Guild Founder',
    description: 'Wealthy merchant and political power broker who helped organize the Trader faction and establish the commercial foundations of expansion.',
    era: Era.TradingExpansion,
    specialization: 'research',
    durationBonus: 0.85,
  },
  eskelGorov: {
    key: 'eskelGorov',
    name: 'Eskel Gorov',
    title: 'Foundation Agent',
    description: 'A Foundation agent captured on Askone whose imprisonment catalyzed Limmar Ponyets\' trading expedition and opened a new market.',
    era: Era.TradingExpansion,
    specialization: 'research',
    durationBonus: 0.85,
  },
  belRiose: {
    key: 'belRiose',
    name: 'Bel Riose',
    title: 'The Last Imperial General',
    description: 'The only Imperial general capable of threatening the Foundation. His brilliance was ultimately undone by the Emperor\'s jealousy, proving Seldon\'s prediction that the Empire\'s own rot would protect the Foundation.',
    era: Era.TradingExpansion,
    specialization: 'mission',
    durationBonus: 0.75,
  },
  lathanDevers: {
    key: 'lathanDevers',
    name: 'Lathan Devers',
    title: 'The Reluctant Hero',
    description: 'A trader who stumbled into the heart of Imperial politics. His daring escape from Trantor with critical intelligence helped turn the tide against Bel Riose\'s invasion.',
    era: Era.TradingExpansion,
    specialization: 'research',
    durationBonus: 0.75,
  },

  // ─── Era 2: Psychological Influence ──────────────────────────────────

  baytaDarell: {
    key: 'baytaDarell',
    name: 'Bayta Darell',
    title: 'Mule\'s Defeater',
    description: 'The woman who single-handedly prevented the Mule from discovering the Second Foundation, altering the course of galactic history through a single act of desperate courage.',
    era: Era.PsychologicalInfluence,
    specialization: 'mission',
    durationBonus: 0.85,
  },
  eblingMis: {
    key: 'eblingMis',
    name: 'Ebling Mis',
    title: 'Psychohistorian',
    description: 'A brilliant psychologist and researcher who nearly located the Second Foundation. His work on psychohistorical mathematics pushed the boundaries of the field.',
    era: Era.PsychologicalInfluence,
    specialization: 'research',
    durationBonus: 0.85,
  },
  hanPritcher: {
    key: 'hanPritcher',
    name: 'Han Pritcher',
    title: 'Converted Captain',
    description: 'A Foundation intelligence officer converted by the Mule. His knowledge of Foundation defenses and strategies made him a formidable operative.',
    era: Era.PsychologicalInfluence,
    specialization: 'mission',
    durationBonus: 0.85,
  },
  preemPalver: {
    key: 'preemPalver',
    name: 'Preem Palver',
    title: 'First Speaker',
    description: 'First Speaker of the Second Foundation and master of mentalic manipulation. He guided galactic events from the shadows to restore the Seldon Plan.',
    era: Era.PsychologicalInfluence,
    specialization: 'research',
    durationBonus: 0.85,
  },
  theMule: {
    key: 'theMule',
    name: 'The Mule',
    title: 'The Unconverted',
    description: 'The mutant warlord whose emotional conversion powers nearly destroyed the Seldon Plan. After his defeat, his understanding of mentalics proved invaluable to Foundation psychologists.',
    era: Era.PsychologicalInfluence,
    specialization: 'mission',
    durationBonus: 0.75,
  },
  arkadyDarell: {
    key: 'arkadyDarell',
    name: 'Arkady Darell',
    title: 'The 14-Year-Old Heroine',
    description: 'Granddaughter of Bayta, Arkady\'s precocious intelligence and daring journey to Trantor helped expose the Second Foundation\'s location \u2014 or so everyone believed.',
    era: Era.PsychologicalInfluence,
    specialization: 'research',
    durationBonus: 0.75,
  },

  // ─── Era 3: Galactic Reunification ───────────────────────────────────

  golanTrevize: {
    key: 'golanTrevize',
    name: 'Golan Trevize',
    title: 'Foundation Councilman',
    description: 'The man chosen by destiny to make the ultimate decision for humanity\'s future. His intuition guided him to choose Galaxia over the Seldon Plan.',
    era: Era.GalacticReunification,
    specialization: 'mission',
    durationBonus: 0.85,
  },
  janovPelorat: {
    key: 'janovPelorat',
    name: 'Janov Pelorat',
    title: 'Mythologist',
    description: 'A scholar of ancient myths and legends whose lifelong research into humanity\'s origins proved essential to locating Earth and understanding Galaxia.',
    era: Era.GalacticReunification,
    specialization: 'research',
    durationBonus: 0.85,
  },
  bliss: {
    key: 'bliss',
    name: 'Bliss',
    title: 'Gaian Ambassador',
    description: 'A component of the planetary consciousness Gaia, sent to accompany Trevize on his journey. Her mentalic abilities and alien perspective shaped the quest.',
    era: Era.GalacticReunification,
    specialization: 'mission',
    durationBonus: 0.85,
  },
  daneelOlivaw: {
    key: 'daneelOlivaw',
    name: 'R. Daneel Olivaw',
    title: 'Guardian of Humanity',
    description: 'The ancient robot who has guided humanity for twenty thousand years. Creator of Gaia, architect of psychohistory, and the hidden hand behind the Seldon Plan.',
    era: Era.GalacticReunification,
    specialization: 'research',
    durationBonus: 0.85,
  },
  storGendibal: {
    key: 'storGendibal',
    name: 'Stor Gendibal',
    title: 'Second Foundation Speaker',
    description: 'A young and ambitious Speaker of the Second Foundation. His confrontation with Gaia forced him to reconsider everything he knew about mentalics and the nature of consciousness.',
    era: Era.GalacticReunification,
    specialization: 'research',
    durationBonus: 0.75,
  },
  fallom: {
    key: 'fallom',
    name: 'Fallom',
    title: 'Child of Solaria',
    description: 'A Solarian hermaphrodite child with extraordinary transducer abilities. Fallom\'s unique biology held the key to merging organic and robotic consciousness for the Galaxia project.',
    era: Era.GalacticReunification,
    specialization: 'mission',
    durationBonus: 0.75,
  },
};

export const ALL_HERO_KEYS = Object.keys(HERO_DEFINITIONS);
