import { ShipDefinition, ShipType, TradeRouteDefinition } from '../types/ships.js';
import { Era } from '../types/eras.js';

export const SHIP_DEFINITIONS: Record<ShipType, ShipDefinition> = {
  freeTrader: {
    type: 'freeTrader',
    name: 'Free Trader',
    description: 'Small, fast trading vessel for running goods between worlds.',
    era: Era.TradingExpansion,
    buildCost: { credits: 10000, rawMaterials: 500 },
    buildTime: 30,
    cargoCapacity: 100,
    speed: 1,
  },
  scoutShip: {
    type: 'scoutShip',
    name: 'Scout Ship',
    description: 'Exploration vessel for discovering new trade routes.',
    era: Era.TradingExpansion,
    buildCost: { credits: 25000, rawMaterials: 1000, nuclearTech: 200 },
    buildTime: 60,
    cargoCapacity: 50,
    speed: 2,
  },
  whisperShip: {
    type: 'whisperShip',
    name: 'Whisper Ship',
    description: 'Covert vessel used by the Second Foundation to project psychological influence across worlds.',
    era: Era.PsychologicalInfluence,
    buildCost: { credits: 500000, rawMaterials: 10000, nuclearTech: 5000 },
    buildTime: 120,
    cargoCapacity: 200,
    speed: 1.5,
  },
  graviticShip: {
    type: 'graviticShip',
    name: 'Gravitic Ship',
    description: 'Advanced vessel using gravitic drive technology from Gaia.',
    era: Era.GalacticReunification,
    buildCost: { credits: 5000000, rawMaterials: 100000, nuclearTech: 50000 },
    buildTime: 300,
    cargoCapacity: 1000,
    speed: 5,
  },
};

export const TRADE_ROUTE_DEFINITIONS: Record<string, TradeRouteDefinition> = {
  terminusLocal: {
    key: 'terminusLocal',
    name: 'Terminus Local',
    description: 'Short trade run around Terminus and the nearby colony worlds.',
    era: Era.TradingExpansion,
    duration: 60,
    reward: { credits: 5000, rawMaterials: 100 },
    unlockCost: { credits: 5000 },
    requiredShipType: 'freeTrader',
  },
  anacreonRun: {
    key: 'anacreonRun',
    name: 'Anacreon Run',
    description: 'Trade route to the Kingdom of Anacreon, exchanging Foundation gadgets for raw materials.',
    era: Era.TradingExpansion,
    duration: 180,
    reward: { credits: 20000, rawMaterials: 500, nuclearTech: 100 },
    unlockCost: { credits: 25000 },
    requiredShipType: 'freeTrader',
  },
  korellianCircuit: {
    key: 'korellianCircuit',
    name: 'Korellian Circuit',
    description: 'Dangerous but lucrative route through Korellian space, trading weapons and technology.',
    era: Era.TradingExpansion,
    duration: 300,
    reward: { credits: 50000, rawMaterials: 2000, nuclearTech: 500 },
    unlockCost: { credits: 100000, influence: 1000 },
    requiredShipType: 'freeTrader',
  },
  peripheryExploration: {
    key: 'peripheryExploration',
    name: 'Periphery Exploration',
    description: 'Scout the outer Periphery for new colony sites and forgotten Imperial installations.',
    era: Era.TradingExpansion,
    duration: 600,
    reward: { knowledge: 5000, influence: 500, rawMaterials: 1000 },
    unlockCost: { credits: 50000, knowledge: 5000 },
    requiredShipType: 'scoutShip',
  },
  imperialRemnant: {
    key: 'imperialRemnant',
    name: 'Imperial Remnant',
    description: 'Covert mission through the ruins of Imperial space, gathering intelligence and lost technology.',
    era: Era.PsychologicalInfluence,
    duration: 900,
    reward: { credits: 500000, knowledge: 50000, nuclearTech: 10000 },
    unlockCost: { credits: 1000000, influence: 10000 },
    requiredShipType: 'whisperShip',
  },
  trantorPilgrimage: {
    key: 'trantorPilgrimage',
    name: 'Trantor Pilgrimage',
    description: 'Journey to the ruins of the old Imperial capital, subtly influencing remnant populations.',
    era: Era.PsychologicalInfluence,
    duration: 1200,
    reward: { credits: 2000000, knowledge: 200000, influence: 50000 },
    unlockCost: { credits: 5000000, knowledge: 100000 },
    requiredShipType: 'whisperShip',
  },
  gaiaExpedition: {
    key: 'gaiaExpedition',
    name: 'Gaia Expedition',
    description: 'Contact the living world of Gaia for gravitic technology exchange.',
    era: Era.GalacticReunification,
    duration: 1800,
    reward: { credits: 50000000, knowledge: 1000000, influence: 500000, nuclearTech: 100000 },
    unlockCost: { credits: 100000000, influence: 1000000 },
    requiredShipType: 'graviticShip',
  },
};

export const ALL_SHIP_TYPES = Object.keys(SHIP_DEFINITIONS) as ShipType[];
export const ALL_TRADE_ROUTE_KEYS = Object.keys(TRADE_ROUTE_DEFINITIONS);
