import { ShipDefinition, ShipType, TradeRouteDefinition } from '../types/ships.js';
import { Era } from '../types/eras.js';

export const SHIP_DEFINITIONS: Record<ShipType, ShipDefinition> = {
  freeTrader: {
    type: 'freeTrader',
    name: 'Free Trader',
    description: 'Small, fast trading vessel for running goods between worlds.',
    era: Era.TradingExpansion,
    buildCost: { credits: 10000, rawMaterials: 1000 },
    buildTime: 30,
    cargoCapacity: 100,
    speed: 1,
  },
  scoutShip: {
    type: 'scoutShip',
    name: 'Scout Ship',
    description: 'Exploration vessel for discovering new trade routes.',
    era: Era.TradingExpansion,
    buildCost: { credits: 25000, rawMaterials: 2000, nuclearTech: 200 },
    buildTime: 60,
    cargoCapacity: 50,
    speed: 2,
  },
  armedMerchant: {
    type: 'armedMerchant',
    name: 'Armed Merchant',
    description: 'Heavily modified Free Trader with weapon pods and reinforced cargo bays for dangerous trade routes.',
    era: Era.TradingExpansion,
    buildCost: { credits: 50000, rawMaterials: 5000, nuclearTech: 500 },
    buildTime: 90,
    cargoCapacity: 200,
    speed: 1.2,
  },
  whisperShip: {
    type: 'whisperShip',
    name: 'Whisper Ship',
    description: 'Covert vessel used by the Second Foundation to project psychological influence across worlds.',
    era: Era.PsychologicalInfluence,
    buildCost: { credits: 500000, rawMaterials: 20000, nuclearTech: 5000 },
    buildTime: 120,
    cargoCapacity: 200,
    speed: 1.5,
  },
  foundationCruiser: {
    type: 'foundationCruiser',
    name: 'Foundation Cruiser',
    description: 'Sleek military vessel with advanced shield arrays and long-range capabilities, designed for deep-space operations.',
    era: Era.PsychologicalInfluence,
    buildCost: { credits: 2000000, rawMaterials: 100000, nuclearTech: 25000 },
    buildTime: 180,
    cargoCapacity: 500,
    speed: 2,
  },
  graviticShip: {
    type: 'graviticShip',
    name: 'Gravitic Ship',
    description: 'Advanced vessel using gravitic drive technology from Gaia.',
    era: Era.GalacticReunification,
    buildCost: { credits: 5000000, rawMaterials: 200000, nuclearTech: 50000 },
    buildTime: 300,
    cargoCapacity: 1000,
    speed: 5,
  },
  solarianYacht: {
    type: 'solarianYacht',
    name: 'Solarian Yacht',
    description: 'Elegant alien craft reverse-engineered from Solarian technology, with energy fins that harness stellar radiation for propulsion.',
    era: Era.GalacticReunification,
    buildCost: { credits: 20000000, rawMaterials: 1000000, nuclearTech: 200000 },
    buildTime: 600,
    cargoCapacity: 2000,
    speed: 8,
  },
};

export const TRADE_ROUTE_DEFINITIONS: Record<string, TradeRouteDefinition> = {
  terminusLocal: {
    key: 'terminusLocal',
    name: 'Terminus Local',
    description: 'Short trade run around Terminus and the nearby colony worlds.',
    era: Era.TradingExpansion,
    duration: 60,
    reward: { credits: 5000, rawMaterials: 100 },
    unlockCost: { credits: 5000 },
    requiredShipType: 'freeTrader',
  },
  anacreonRun: {
    key: 'anacreonRun',
    name: 'Anacreon Run',
    description: 'Trade route to the Kingdom of Anacreon, exchanging Foundation gadgets for raw materials.',
    era: Era.TradingExpansion,
    duration: 180,
    reward: { credits: 20000, rawMaterials: 500, nuclearTech: 100 },
    unlockCost: { credits: 25000 },
    requiredShipType: 'freeTrader',
  },
  korellianCircuit: {
    key: 'korellianCircuit',
    name: 'Korellian Circuit',
    description: 'Dangerous but lucrative route through Korellian space, trading weapons and technology.',
    era: Era.TradingExpansion,
    duration: 300,
    reward: { credits: 50000, rawMaterials: 2000, nuclearTech: 500 },
    unlockCost: { credits: 100000, influence: 1000 },
    requiredShipType: 'freeTrader',
  },
  peripheryExploration: {
    key: 'peripheryExploration',
    name: 'Periphery Exploration',
    description: 'Scout the outer Periphery for new colony sites and forgotten Imperial installations.',
    era: Era.TradingExpansion,
    duration: 600,
    reward: { knowledge: 5000, influence: 500, rawMaterials: 1000 },
    unlockCost: { credits: 50000, knowledge: 5000 },
    requiredShipType: 'scoutShip',
  },
  siwennaRun: {
    key: 'siwennaRun',
    name: 'Siwenna Run',
    description: 'A dangerous but profitable route through Siwennan space, trading Foundation technology for rare resources under Imperial noses.',
    era: Era.TradingExpansion,
    duration: 450,
    reward: { credits: 100000, knowledge: 5000, influence: 2000 },
    unlockCost: { credits: 75000, influence: 2000 },
    requiredShipType: 'armedMerchant',
  },
  imperialRemnant: {
    key: 'imperialRemnant',
    name: 'Imperial Remnant',
    description: 'Covert mission through the ruins of Imperial space, gathering intelligence and lost technology.',
    era: Era.PsychologicalInfluence,
    duration: 900,
    reward: { credits: 500000, knowledge: 50000, nuclearTech: 10000 },
    unlockCost: { credits: 1000000, influence: 10000 },
    requiredShipType: 'whisperShip',
  },
  trantorPilgrimage: {
    key: 'trantorPilgrimage',
    name: 'Trantor Pilgrimage',
    description: 'Journey to the ruins of the old Imperial capital, subtly influencing remnant populations.',
    era: Era.PsychologicalInfluence,
    duration: 1200,
    reward: { credits: 2000000, knowledge: 200000, influence: 50000 },
    unlockCost: { credits: 5000000, knowledge: 100000 },
    requiredShipType: 'whisperShip',
  },
  kalganReconnaissance: {
    key: 'kalganReconnaissance',
    name: 'Kalgan Reconnaissance',
    description: 'Deep reconnaissance mission to the former seat of the Mule\'s empire, now a fractured collection of warlord states ripe for Foundation influence.',
    era: Era.PsychologicalInfluence,
    duration: 1500,
    reward: { credits: 2000000, knowledge: 100000, influence: 20000, nuclearTech: 50000 },
    unlockCost: { credits: 3000000, nuclearTech: 50000 },
    requiredShipType: 'foundationCruiser',
  },
  gaiaExpedition: {
    key: 'gaiaExpedition',
    name: 'Gaia Expedition',
    description: 'Contact the living world of Gaia for gravitic technology exchange.',
    era: Era.GalacticReunification,
    duration: 1800,
    reward: { credits: 50000000, knowledge: 1000000, influence: 500000, nuclearTech: 100000 },
    unlockCost: { credits: 100000000, influence: 1000000 },
    requiredShipType: 'graviticShip',
  },
  earthExpedition: {
    key: 'earthExpedition',
    name: 'Earth Expedition',
    description: 'The ultimate voyage: a journey to find the legendary origin world of humanity. Myths say Earth is radioactive, hidden, or simply lost — but the Solarian Yacht\'s advanced sensors may succeed where all others have failed.',
    era: Era.GalacticReunification,
    duration: 3600,
    reward: { credits: 200000000, knowledge: 5000000, influence: 2000000, nuclearTech: 500000 },
    unlockCost: { credits: 500000000, knowledge: 5000000 },
    requiredShipType: 'solarianYacht',
  },
};

export const ALL_SHIP_TYPES = Object.keys(SHIP_DEFINITIONS) as ShipType[];
export const ALL_TRADE_ROUTE_KEYS = Object.keys(TRADE_ROUTE_DEFINITIONS);
